### ISSUE TITLE
ATP error when no ATP option selected

### ISSUE THREAD

**Issue by technotherion** [Menithal/Blender-Hifi-Addon#10]
Using version 0.4.5 - exporting a test avatar. 
```
Modules Installed from 'C:\\Users\\OrangeTwo\\Downloads\\Blender-Hifi-Addon-master(3).zip' into 'C:\\Users\\OrangeTwo\\AppData\\Roaming\\Blender Foundation\\Blender\\2.78\\scripts\\addons' ()
Traceback (most recent call last):
  File "C:\Users\OrangeTwo\AppData\Roaming\Blender Foundation\Blender\2.78\scripts\addons\Blender-Hifi-Addon-master\hifi_json_writer.py", line 399, in execute
    if self.clone_scene:
Exception: You must Use ATP or Set the Marketplace / base URL to make sure that the content can be reached after you upload it. ATP currently not supported

location: <unknown location>:-1

Traceback (most recent call last):
  File "C:\Users\OrangeTwo\AppData\Roaming\Blender Foundation\Blender\2.78\scripts\addons\Blender-Hifi-Addon-master\hifi_json_writer.py", line 399, in execute
    if self.clone_scene:
Exception: You must Use ATP or Set the Marketplace / base URL to make sure that the content can be reached after you upload it. ATP currently not supported

location: <unknown location>:-1

```

These are my export options:
![image](https://user-images.githubusercontent.com/13829537/37380417-e7e1680e-26f5-11e8-86c4-1a1a0685082e.png)

**Comment by Menithal** [comment]
Yep this works as intend. You have to either override the marketplace url or set "use ATP" because otherwise the urls generated is incorrect. The requirement will be removed once relative json patching is supported in high Fidelity

**Comment by Menithal** [comment]
However I do know that the error message may throw people off so I might change what happens there to a reminder instead of warning

**Comment by Menithal** [comment]
Also the feature is not yet for exporting avatars just scenes :D I need to make that probably more clear

**Comment by technotherion** [comment]
Yep; I get the distinction now :) Just initially I was trying to use it to export other things as well!!
