### ISSUE TITLE
'Set Bone Physical' bone renaming truncates the name

### ISSUE THREAD

**Issue by NebuHiiEjamu** [Menithal/Blender-Hifi-Addon#19]
I have a model I'm preparing to turn into a HiFi avatar. The hair joints are named 'hair 0', 'hair 1', 'hair 2', etc. However, selecting them and clicking 'set bone physical' renames them to 'sim0', 'sim1', etc. It would appear the addon is truncating spaced bone names and assigning them a number instead. This is not only vague, but problematic, because if I want to set bone physical to other bones with similar names, I'll get 'sim1.001', 'sim2.001', etc.

My recommendation is to strip spaces and/or use regex for this, perhaps.

**Comment by Menithal** [comment]
Odd I though I had fixed this in the recent release. This was occurring in that correct?

**Comment by NebuHiiEjamu** [comment]
1.2, yes

**Comment by Menithal** [comment]
Ok will look into it. Thanks

**Comment by Menithal** [comment]
Give 1.2.1 a try

**Comment by Menithal** [comment]
This should be solved in 1.2, and double made sure of in 1.2.3
