### ISSUE TITLE
Albedo defaults to white, even with no albedo texture

### ISSUE THREAD

**Issue by SilverfishVR** [Menithal/Blender-Hifi-Addon#23]
on "hifi FBX" export the albedo /Base Color value defaults to white (1,1,1) even if there is no albedo texture plugged in. I know this is part of the effort to prevent accidental tinting but is should really only do this if a texture is plugged in.
Personally, I would like for this to be an optional feature because I ability to tint a texture this way quite useful.

plugin V1.5.5
Blender 2.80
hifi 0.86.0

**Comment by Menithal** [comment]
Fixed in the 2.0 version.
