### ISSUE TITLE
"hifi" fbx export broken again

### ISSUE THREAD

**Issue by SilverfishVR** [Menithal/Blender-Hifi-Addon#26]
Sorry to say that the import/export system changed again in Blender 1.82 (release) so the HIFI fbx export broke, the options part is missing from the dialog (like path mode etc.).
Clicking export just throws a ton of exceptions.

**Comment by Menithal** [comment]
Aw fantastic.

I think ill have to just copy the fbx exporter instead of using the existing one to have it stable throughout all the version changes and changes to the io_fbx library. :P
